import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import BlankComponent from "@/components/BlankComponent";
// import CompanyDetails from "@/components/CompanyDetails";
// import CompanyDetails2 from "@/components/CompanyDetails2";

import dynamic from "next/dynamic";

const CompanyDetails2 = dynamic(() => import("@/components/CompanyDetails2"), { ssr: false });
const CompanyDetails = dynamic(() => import("@/components/CompanyDetails"), { ssr: false });

export default function Home() {
  return (
    <>
      <Head>
        <title>Blue Bird</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* <BlankComponent text="Scroll Down" /> */}
        {/* <CompanyDetails /> */}
        <CompanyDetails2 />
        {/* <BlankComponent text="Scroll Up" /> */}
      </div>
    </>
  );
}
